
# --------------- USER DETAILS -----------
CREATE TABLE IF NOT EXISTS User (
  email            VARCHAR(255)     PRIMARY KEY,
  name             VARCHAR(255)     NOT NULL,
  password         VARCHAR(255)     NOT NULL,
  balance          DECIMAL(10,2)    NOT NULL,
  deleted          BOOLEAN          DEFAULT FALSE,
  created_ts       TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_ts       TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);

 # --------------- ASSET_CODE DETAILS -----------
CREATE TABLE IF NOT EXISTS AssetCode (
  asset_code       VARCHAR(255)     PRIMARY KEY,
  asset_name       VARCHAR(255)     NOT NULL,
  deleted          BOOLEAN          DEFAULT FALSE,
  created_ts       TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_ts       TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);

  # --------------- USER_ASSET DETAILS -----------
CREATE TABLE IF NOT EXISTS UserAsset (
  email             VARCHAR(255)    NOT NULL,
  asset_code        VARCHAR(255)    NOT NULL,
  quantity          INT             DEFAULT 0 NOT NULL,
  deleted           BOOLEAN         DEFAULT FALSE,
  created_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (email, asset_code),
);

# --------------- ASSET DETAILS -----------
CREATE TABLE IF NOT EXISTS Asset (
  date              TIMESTAMP(6)    NOT NULL,
  currency          VARCHAR(255)    NOT NULL,
  asset_code        VARCHAR(255)    NOT NULL,
  performance       DECIMAL(10,2)   NOT NULL,
  value             DECIMAL(10,2)   NOT NULL,
  weight_unit       VARCHAR(255),
  deleted           BOOLEAN         DEFAULT FALSE,
  created_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (date, currency, asset_code)
);

# --------------- TRANSACTION DETAILS -----------
CREATE TABLE IF NOT EXISTS Transactions (
  transaction_id    VARCHAR(255)    PRIMARY KEY,
  transaction_type  VARCHAR(255)    NOT NULL,
  email             VARCHAR(255)    NOT NULL,
  status            VARCHAR(255)    NOT NULL,
  amount            DECIMAL(10,2)   NOT NULL,
  asset_code        VARCHAR(255)    NOT NULL,
  currency          VARCHAR(255)    NOT NULL,
  quantity          INT             NOT NULL,
  deleted           BOOLEAN         DEFAULT FALSE,
  created_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_ts        TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


